(setq my-user-emacs-directory user-emacs-directory)

(require 'init-core)
(require 'init-functions)
(require 'init-packages)
(require 'init-editor)
(require 'init-evil)
(require 'init-auto-complete)
(require 'init-projectile)
(require 'init-helm)
(require 'init-ido)
(require 'init-git)
(require 'init-vim)
(require 'init-markdown)
(require 'init-bindings)
(require 'init-flycheck)
(require 'init-eyecandy)

;;; (unload-feature 'foo)
