(require-package 'smart-mode-line)
(require 'smart-mode-line)
(if after-init-time (sml/setup)
  (add-hook 'after-init-hook 'sml/setup))

(require-package 'diminish)
(require 'diminish)
(after 'undo-tree (diminish 'undo-tree-mode))
(after 'auto-complete (diminish 'auto-complete-mode))
(after 'projectile (diminish 'projectile-mode))
(after 'yasnippet (diminish 'yas-minor-mode))
(after 'guide-key (diminish 'guide-key-mode))
(after 'eldoc (diminish 'eldoc-mode))
(after 'smartparens (diminish 'smartparens-mode))
(after 'company (diminish 'company-mode))
(after 'git-gutter+ (diminish 'git-gutter+-mode))

(when (display-graphic-p)
  (set-face-attribute 'default nil :font "Ubuntu Mono-14")
  (fringe-mode 16))

(global-hl-line-mode +1)
(require 'linum)
(global-linum-mode t)
(setq linum-format "%4d ")

(provide 'init-eyecandy)
